/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osdg_game2d_Sprite */

#ifndef _Included_org_osdg_game2d_Sprite
#define _Included_org_osdg_game2d_Sprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osdg_game2d_Sprite
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_osdg_game2d_Sprite_createNativeObject__
  (JNIEnv *, jobject);

/*
 * Class:     org_osdg_game2d_Sprite
 * Method:    createNativeObject
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_osdg_game2d_Sprite_createNativeObject__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
