/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osdg_game2d_Node */

#ifndef _Included_org_osdg_game2d_Node
#define _Included_org_osdg_game2d_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osdg_game2d_Node
 * Method:    addChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_osdg_game2d_Node_addChild
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_osdg_game2d_Node
 * Method:    setPosition
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_org_osdg_game2d_Node_setPosition
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     org_osdg_game2d_Node
 * Method:    runAction
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_osdg_game2d_Node_runAction
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
