/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osdg_game2d_Label */

#ifndef _Included_org_osdg_game2d_Label
#define _Included_org_osdg_game2d_Label
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osdg_game2d_Label
 * Method:    nativeSetString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_osdg_game2d_Label_nativeSetString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_osdg_game2d_Label
 * Method:    setSystemFontSize
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_osdg_game2d_Label_setSystemFontSize
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_osdg_game2d_Label
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_osdg_game2d_Label_createNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
