/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osdg_game2d_Scene */

#ifndef _Included_org_osdg_game2d_Scene
#define _Included_org_osdg_game2d_Scene
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osdg_game2d_Scene
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_osdg_game2d_Scene_createNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
