/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osdg_game2d_actions_MoveBy */

#ifndef _Included_org_osdg_game2d_actions_MoveBy
#define _Included_org_osdg_game2d_actions_MoveBy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osdg_game2d_actions_MoveBy
 * Method:    createNativeObject
 * Signature: (FFF)J
 */
JNIEXPORT jlong JNICALL Java_org_osdg_game2d_actions_MoveBy_createNativeObject
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
